import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/atoms/Header";
import MyApp from "./_app";
import { nunito_sans, poppins, roboto_slab } from "./utils/fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>Product Hunt Firebase y Next.js</title>
      <body className={`${nunito_sans} ${poppins} ${roboto_slab}`}>
        <Header />
        <main>
          <MyApp>{children}</MyApp>
        </main>
      </body>
    </html>
  );
}
